title: The Messy Kitchen
author: AYGros
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A realistic blog about cooking and baking at home, without polished arranged pictures but adressing real life issues.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
